title: "[Ideas] "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: "Thanks for sharing your idea or proposing new features!"
  - type: textarea
    attributes:
      label: Description
      description: A short description of your feature.
  - type: textarea
    attributes:
      label: Use case/motivation
      description: What would you like to happen?
      placeholder: >
          Rather than telling us how you might implement this feature, try to take a
          step back and describe what you are trying to achieve.
  - type: textarea
    attributes:
      label: Related issues
      description: Is there currently another issue associated with this?
  - type: checkboxes
    attributes:
      label: Are you willing to submit a PR?
      options:
        - label: Yes I am willing to submit a PR!
  - type: markdown
    attributes:
      value: "Thanks for sharing!"
