name: cbdb pipeline
on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
    branches:    
      - main
      - union_store_catalog
  
env:
  BUILD_TYPE: "debug"
  FTS_MODE: "internal_fts"
  DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
  DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}

permissions:
  id-token: write
  contents: read
jobs:
  build:
    if: github.event.pull_request.draft == false
    runs-on: [self-hosted, example]
    steps:
      - uses: actions/checkout@v3
      - name: Run build script
        run: |
          echo $GITHUB_RUN_ID > BUILD_NUMBER
          hd-ci/compile_cbdb.bash ${GEN_DOCKER_TAG}
      - uses: actions/upload-artifact@v3
        with:
          name: cbdb-variables
          path: /opt/actions-runner/_work/cloudberrydb/cloudberrydb/cbdb-artifacts.txt
      - uses: actions/upload-artifact@v3
        with:
          name: cbdb-package
          path: /tmp/server-build*
  icw-test:
    needs: build
    runs-on: [self-hosted, example]
    env:
      MAKE_TEST_COMMAND: "-k PGOPTIONS='-c optimizer=off -c gp_appendonly_insert_files=0' installcheck-world"
      TEST_OS: "centos"
      DUMP_DB: "true"
    steps:
      - uses: actions/checkout@v3
        with:
          path: "gpdb_src"
      - uses: actions/download-artifact@v3
        with:
          name: cbdb-variables
          path: /opt/
      - uses: actions/download-artifact@v3
        with:
          name: cbdb-package
          path: /opt/
      - name: Run icw-test script
        run: |
          mkdir /code
          cp -a gpdb_src/ /code
          cd /code
          echo $GITHUB_RUN_ID > gpdb_src/BUILD_NUMBER
          gpdb_src/hd-ci/icw_cbdb.bash $FTS_MODE
      - uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: cbdb-test-log
          path: | 
            /opt/actions-runner/_work/cloudberrydb/cloudberrydb/cbdb-artifacts.txt
            /opt/actions-runner/_work/cloudberrydb/cloudberrydb/src/test/regress/regression.out
            /opt/actions-runner/_work/cloudberrydb/cloudberrydb/src/test/regress/regression.diffs
            /opt/actions-runner/_work/cloudberrydb/cloudberrydb/src/test/regress/results/
            /opt/actions-runner/_work/cloudberrydb/cloudberrydb/src/test/regress/expected/
            /opt/actions-runner/_work/cloudberrydb/cloudberrydb/src/test/isolation2/regression.out
            /opt/actions-runner/_work/cloudberrydb/cloudberrydb/src/test/isolation2/regression.diffs
            /opt/actions-runner/_work/cloudberrydb/cloudberrydb/src/test/isolation2/results/
            /opt/actions-runner/_work/cloudberrydb/cloudberrydb/src/test/isolation2/expected/
            /opt/actions-runner/_work/cloudberrydb/cloudberrydb/gpAux/gpdemo/datadirs/standby/log/
            /opt/actions-runner/_work/cloudberrydb/cloudberrydb/gpAux/gpdemo/datadirs/qddir/demoDataDir-1/log/
            /opt/actions-runner/_work/cloudberrydb/cloudberrydb/gpAux/gpdemo/datadirs/dbfast1/demoDataDir0/log/
            /opt/actions-runner/_work/cloudberrydb/cloudberrydb/gpAux/gpdemo/datadirs/dbfast2/demoDataDir1/log/
            /opt/actions-runner/_work/cloudberrydb/cloudberrydb/gpAux/gpdemo/datadirs/dbfast3/demoDataDir2/log/
            /opt/actions-runner/_work/cloudberrydb/cloudberrydb/gpAux/gpdemo/datadirs/dbfast_mirror1/demoDataDir0/log/
            /opt/actions-runner/_work/cloudberrydb/cloudberrydb/gpAux/gpdemo/datadirs/dbfast_mirror2/demoDataDir1/log/
            /opt/actions-runner/_work/cloudberrydb/cloudberrydb/gpAux/gpdemo/datadirs/dbfast_mirror3/demoDataDir2/log/
  icw-orca-test:
    needs: build
    runs-on: [self-hosted, example]
    env:
      MAKE_TEST_COMMAND: "-k PGOPTIONS='-c optimizer=on -c gp_appendonly_insert_files=0' installcheck-world"
      TEST_OS: "centos"
      DUMP_DB: "true"
    steps:
      - uses: actions/checkout@v3
        with:
          path: "gpdb_src"
      - uses: actions/download-artifact@v3
        with:
          name: cbdb-variables
          path: /opt/
      - uses: actions/download-artifact@v3
        with:
          name: cbdb-package
          path: /opt/
      - name: Run icw-orca-test script
        run: |
          mkdir /code
          cp -a gpdb_src/ /code
          cd /code
          echo $GITHUB_RUN_ID > gpdb_src/BUILD_NUMBER
          gpdb_src/hd-ci/icw_cbdb.bash $FTS_MODE
      - uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: cbdb-test-log
          path: | 
            /opt/actions-runner/_work/cloudberrydb/cloudberrydb/cbdb-artifacts.txt
            /opt/actions-runner/_work/cloudberrydb/cloudberrydb/src/test/regress/regression.out
            /opt/actions-runner/_work/cloudberrydb/cloudberrydb/src/test/regress/regression.diffs
            /opt/actions-runner/_work/cloudberrydb/cloudberrydb/src/test/regress/results/
            /opt/actions-runner/_work/cloudberrydb/cloudberrydb/src/test/regress/expected/
            /opt/actions-runner/_work/cloudberrydb/cloudberrydb/src/test/isolation2/regression.out
            /opt/actions-runner/_work/cloudberrydb/cloudberrydb/src/test/isolation2/regression.diffs
            /opt/actions-runner/_work/cloudberrydb/cloudberrydb/src/test/isolation2/results/
            /opt/actions-runner/_work/cloudberrydb/cloudberrydb/src/test/isolation2/expected/
            /opt/actions-runner/_work/cloudberrydb/cloudberrydb/gpAux/gpdemo/datadirs/standby/log/
            /opt/actions-runner/_work/cloudberrydb/cloudberrydb/gpAux/gpdemo/datadirs/qddir/demoDataDir-1/log/
            /opt/actions-runner/_work/cloudberrydb/cloudberrydb/gpAux/gpdemo/datadirs/dbfast1/demoDataDir0/log/
            /opt/actions-runner/_work/cloudberrydb/cloudberrydb/gpAux/gpdemo/datadirs/dbfast2/demoDataDir1/log/
            /opt/actions-runner/_work/cloudberrydb/cloudberrydb/gpAux/gpdemo/datadirs/dbfast3/demoDataDir2/log/
            /opt/actions-runner/_work/cloudberrydb/cloudberrydb/gpAux/gpdemo/datadirs/dbfast_mirror1/demoDataDir0/log/
            /opt/actions-runner/_work/cloudberrydb/cloudberrydb/gpAux/gpdemo/datadirs/dbfast_mirror2/demoDataDir1/log/
            /opt/actions-runner/_work/cloudberrydb/cloudberrydb/gpAux/gpdemo/datadirs/dbfast_mirror3/demoDataDir2/log/
  icw-parallel-test:
    needs: build
    runs-on: [self-hosted, example]
    env:
      MAKE_TEST_COMMAND: "-C src/test/regress -k PGOPTIONS='-c gp_appendonly_insert_files=0' installcheck-cbdb-parallel"
      TEST_OS: "centos"
      DUMP_DB: "true"
    steps:
      - uses: actions/checkout@v3
        with:
          path: "gpdb_src"
      - uses: actions/download-artifact@v3
        with:
          name: cbdb-variables
          path: /opt/
      - uses: actions/download-artifact@v3
        with:
          name: cbdb-package
          path: /opt/
      - name: Run icw-parallel-test script
        run: |
          mkdir /code
          cp -a gpdb_src/ /code
          cd /code
          echo $GITHUB_RUN_ID > gpdb_src/BUILD_NUMBER
          gpdb_src/hd-ci/icw_cbdb.bash $FTS_MODE
      - uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: cbdb-test-log
          path: | 
            /opt/actions-runner/_work/cloudberrydb/cloudberrydb/cbdb-artifacts.txt
            /opt/actions-runner/_work/cloudberrydb/cloudberrydb/src/test/regress/regression.out
            /opt/actions-runner/_work/cloudberrydb/cloudberrydb/src/test/regress/regression.diffs
            /opt/actions-runner/_work/cloudberrydb/cloudberrydb/src/test/regress/results/
            /opt/actions-runner/_work/cloudberrydb/cloudberrydb/src/test/regress/expected/
            /opt/actions-runner/_work/cloudberrydb/cloudberrydb/src/test/isolation2/regression.out
            /opt/actions-runner/_work/cloudberrydb/cloudberrydb/src/test/isolation2/regression.diffs
            /opt/actions-runner/_work/cloudberrydb/cloudberrydb/src/test/isolation2/results/
            /opt/actions-runner/_work/cloudberrydb/cloudberrydb/src/test/isolation2/expected/
            /opt/actions-runner/_work/cloudberrydb/cloudberrydb/gpAux/gpdemo/datadirs/standby/log/
            /opt/actions-runner/_work/cloudberrydb/cloudberrydb/gpAux/gpdemo/datadirs/qddir/demoDataDir-1/log/
            /opt/actions-runner/_work/cloudberrydb/cloudberrydb/gpAux/gpdemo/datadirs/dbfast1/demoDataDir0/log/
            /opt/actions-runner/_work/cloudberrydb/cloudberrydb/gpAux/gpdemo/datadirs/dbfast2/demoDataDir1/log/
            /opt/actions-runner/_work/cloudberrydb/cloudberrydb/gpAux/gpdemo/datadirs/dbfast3/demoDataDir2/log/
            /opt/actions-runner/_work/cloudberrydb/cloudberrydb/gpAux/gpdemo/datadirs/dbfast_mirror1/demoDataDir0/log/
            /opt/actions-runner/_work/cloudberrydb/cloudberrydb/gpAux/gpdemo/datadirs/dbfast_mirror2/demoDataDir1/log/
            /opt/actions-runner/_work/cloudberrydb/cloudberrydb/gpAux/gpdemo/datadirs/dbfast_mirror3/demoDataDir2/log/



